### ISSUE TITLE
[Feature Request] Set Failover MS/GW Task

### ISSUE THREAD

**Issue by Basanon** [thekevinholman/SCOM.Management#1]
Hi Kevin
Great MP, really useful for SCOM Admins! Thanks a lot for making it

I just wonder, is there any chance to add task in this MP, for configuring failover management server or GW?

It will be really great feature, since failover configuration already visible in dashboard

Thanks!

**Comment by thekevinholman** [comment]
I am not sure a task is the right solution here - how often would anyone use this?
