### ISSUE TITLE
ConfigMgr PXE Responder Service (SccmPxe) service

### ISSUE THREAD

**Issue by KONIKPK** [thekevinholman/SCOM.Management#5]
This monitor checks the service status of the ConfigMgr PXE Responder Service (SccmPxe) service its WDSServer.
There is no service with this name and we use PXE boot.

**Comment by blakedrumm** [comment]
> This monitor checks the service status of the ConfigMgr PXE Responder Service (SccmPxe) service its WDSServer. There is no service with this name and we use PXE boot.

You would probably have better chances of a response if you commented on his blog post instead:
[https://kevinholman.com/2017/05/09/scom-management-mp-making-a-scom-admins-life-a-little-easier/](https://kevinholman.com/2017/05/09/scom-management-mp-making-a-scom-admins-life-a-little-easier/)

**Comment by thekevinholman** [comment]
Closing - wrong package
